### ISSUE TITLE
BEM-loader for postcss

### ISSUE THREAD

**Issue by kovchiy** [bem/create-bem-react-app#10]
If I want to use css-globals or parent block styles I have to write this:

```css
/* NavBar-Item.css */

@import '../Globals/Globals.css';
@import '../NavBar.css';

.NavBar-Item {
    background: $color-brand;
    width: $navbar-width;
}
```

But I think this would be better:

```css
/* NavBar-Item.css */

@import 'b:Globals';
@import 'b:NavBar';

.NavBar-Item {
    background: $color-brand;
    width: $navbar-width;
}
```
